### ISSUE TITLE
Can't install Cocoapods on build env

### ISSUE THREAD

**Issue by AnoxySoftware** [bitrise-steplib/steps-cocoapods-install#41]
```
System installed cocoapods version:
$ pod "--version"
rbenv: version `2.4.1' is not installed (set by /Users/vagrant/git/.ruby-version)
Command failed, error: exit status 1
```

This is the error we are getting after updating our Workflow Editor Stack to `Xcode 10.2.x` on `Mojave`

**Comment by fehersanyi-bitrise** [comment]
Hello @AnoxySoftware could you please send us this build's url so we could check out the full logs for some more details, and try to come up with a possible solution? 🙃

**Comment by AnoxySoftware** [comment]
@fehersanyi-bitrise https://app.bitrise.io/build/a69e93050cfff835

Thank you

**Comment by AnoxySoftware** [comment]
@fehersanyi-bitrise any Update on this?

**Comment by fehersanyi-bitrise** [comment]
Hello there, sorry, yes so the installed rbenv is 1.1.2 and you need 2.4.1. you can install it from a script step like
`rbenv install 2.4.1`

**Comment by AnoxySoftware** [comment]
Thx @fehersanyi-bitrise 
The issue though seemed to be we had a `.ruby-version` in our project that was setting it to `2.4.1` 
Removed it now from project and it seems to compile again

**Comment by fehersanyi-bitrise** [comment]
Hey @AnoxySoftware sounds good 🙃 I'm glad you could solve it!

**Comment by markotl88** [comment]
Hello, @fehersanyi-bitrise. I'm having the same problem after updating stack to Xcode 10.2 on Mojave.
I added `rbenv install 2.4.1` to the script step, after that it was looking for ruby 2.5.1. I've changed the script again - than it was looking for version 2.5.3. After installing 2.5.3. it now looks for 2.5.1. It seems that I'm being caught in vicious circle here.

Here's the app link: https://app.bitrise.io/app/0194b82c91803ad7# (Bitrise support is on).

@AnoxySoftware Can you please tell me how did you manage to remove the ruby version setting from project? I checked Gemfile/Gemfile.lock, it seems that there's no explicit ruby version setting.

**Comment by AnoxySoftware** [comment]
@markotl88 I just removed the `.ruby-version` file from our project.
This is a hidden file. So search your project for this file (make sure your Finder is set to show Hidden files) and then delete it.

**Comment by markotl88** [comment]
Thanks @AnoxySoftware! Removing .ruby-version file from project resolved my problem too.
