### ISSUE TITLE
pod install doesn't use cocoapods plugins

### ISSUE THREAD

**Issue by kylefleming** [bitrise-steplib/steps-cocoapods-install#43]
I have a `Gemfile`/`Gemfile.lock` that specifies CocoaPods and also specifies a specific version of `cocoapods-binary`, a CocoaPods plugin. The `steps-cocoapods-install` bitrise step seems to run `pod install` directly instead of using `bundle exec pod install` which leads to the `cocoapods-binary` plugin not being found since it was installed through bundler.

As a solution, I would suggest that `bundle exec` should be used for all `pod` commands if the `Gemfile` exists, since that is most likely the intent for any repo that specifies CocoaPods in the `Gemfile`.

**Comment by bitce** [comment]
Hi @kylefleming! 

Thanks for the report and your suggestion! Can you please send us a build URL of this issue happening?

**Comment by kylefleming** [comment]
Sure thing: https://app.bitrise.io/build/98e31eeb2ad789f1

**Comment by lpusok** [comment]
Hi @kylefleming,
Thanks for the report. As long the cocoapods version in the Podfile.lock and Gemfile.lock matches, it should not be a problem and indeed the preferred way. Additionally the step would run the bundle install command internally if implemented.
Can you share the specific Podfile.lock / Podfile  Gemfile.lock / Gemfile used?

**Comment by YutoMizutani** [comment]
Hi,
I agree with @kylefleming .

CocoaPods allows any plugins ( https://guides.cocoapods.org/plugins/setting-up-plugins.html ) and gems are required to run them.
In this case, failed to run the plugin ( `cocoapods-binary` ) installed by `Gemfile.lock` and `cocoapods` was excuted on system environment.

where the versions specified with this line ( https://github.com/bitrise-steplib/steps-cocoapods-install/blob/1a276f4ffcf6efd1fcff11fdbcacb9c08993723f/main.go#L340 ), but not specified environment.

So current my solutions:
Added `Script` Step and written `gem install 'cocoapods-binary'` and install `cocoapods-binary` into global environment.

**Comment by kylefleming** [comment]
@lpusok Sure thing. Here's an example repo that demonstrates the issue: https://github.com/kylefleming/CocoaPodsBitriseIssue

**Comment by trapacska** [comment]
Hey @kylefleming !

Is this issue still persist? I tried with your sample project and it looks to work just fine.

**Comment by trapacska** [comment]
The issue seems to be fixed and a new release is on the way out now with this PR: https://github.com/bitrise-steplib/steps-cocoapods-install/pull/55

So I close this issue as resolved but feel free to re-open if you still encounter any issues with it.
