### ISSUE TITLE
Cocoapods-binary finishes suddenly with error code 1

### ISSUE THREAD

**Issue by MaciejOlejnik** [bitrise-steplib/steps-cocoapods-install#45]
Hey, after I added cocoapods-binary plugin into the cocoapods, `pod install --verbose` command exits with "exit code 1" without any information why (in verbose mode).

I added 'cocoapods-binary' to Gemfile, and seems cocoapods detect plugin correctly.
Bitrise logs looks like:
```
Prebuilding ActionSheetPicker-3.0...
- ActionSheetPicker-3.0, 2.2.0
// other libs here
Command failed, error: exit status 1
```
Before change Cocoapods have builded correctly. On Macbook it prebuilds frameworks successfully.

**My Env**
```
   CocoaPods : 1.7.5
       Xcode : 10.2.1 (10E1001)
cocoapods-binary      : 0.4.4
plugin 'cocoapods-binary'
```
**Config:**
```
plugin 'cocoapods-binary'

platform :ios, '11.2'
use_frameworks!
inhibit_all_warnings!

# Please ensure that libs with bundles are not binary (:binary => false)
all_binary!

abstract_target 'Parent' do
  pod 'Charts', '3.3.0'
  pod 'IQKeyboardManager', '6.4.0', :binary => false
  pod 'IQKeyboardManagerSwift', '6.4.0', :binary => false
   //...

  #  Child target
  target 'child' do
  end
end
```

**Comment by j796160836** [comment]
Hi @MaciejOlejnik,
I also both use **Bitrise** and **Cocoapods-binary**.
It failed because environment doesn't have install cocoapods-binary.

Here is solution,
You have to add a `Script Runner` step for your workflow BEFORE `Run CocoaPods install` step.
Command is 

```
#!/usr/bin/env bash
gem install cocoapods-binary
```

![Screen Shot 2019-10-16 at 3 34 43 PM](https://user-images.githubusercontent.com/686478/66897924-a344d280-f02a-11e9-8c4e-493e460d3934.png)

Then try again. 😉

**Comment by YutoMizutani** [comment]
It is the same issue on https://github.com/bitrise-steplib/steps-cocoapods-install/issues/43 and its fixed at https://github.com/bitrise-steplib/steps-cocoapods-install/releases/tag/1.9.0.
Please specify steps-cocoapods-install@1.9.0 or latest version and try again :smile:

**Comment by trapacska** [comment]
Hi!

I close this issue as it seems to be resolved. Feel free to  reopen if you encounter any issues with it.
