### ISSUE TITLE
Option to trigger `pod update` instead of `pod install`?

### ISSUE THREAD

**Issue by rickmanelius** [bitrise-steplib/steps-cocoapods-install#49]
In React Native 0.61, we're seeing issues with running pod install vs pod update, but the step doesn't appear to have a flag to switch between the two. We're going to move towards the more generic script step in the meantime, but it would be great if we could toggle between the two.

The distinction is noted here https://guides.cocoapods.org/using/pod-install-vs-update.html.

**Comment by Roland-Bak** [comment]
Thank, @rickmanelius!
Your request has been passed to the Tooling Team who will take a look at it! :)

**Comment by rickmanelius** [comment]
Excellent! We had this come up again this morning, so it would be useful.

**Comment by gabrieldonadel** [comment]
Any updates on this?

**Comment by godrei** [comment]
Hi @rickmanelius and @gabrieldonadel ,
sorry for my late response!

We released a new version (`2.2.0`) that addresses this issue, via the new `CocoaPods command`, see the [release note](https://github.com/bitrise-steplib/steps-cocoapods-install/releases/tag/2.2.0) and the [related PR](https://github.com/bitrise-steplib/steps-cocoapods-install/pull/68) for more info.
