### ISSUE TITLE
iOS - CocoaPods requires your terminal to be using UTF-8 encoding - after latest flutter upgrade

### ISSUE THREAD

**Issue by ShrutiThakur01** [bitrise-steplib/steps-cocoapods-install#53]
i am getting this error since yesterday after i upgraded flutter.Before upgrade everything was working normal on both iOS and android. Now my project is not building in iOS. below is my terminal info.

pod setup --verbose

 ```
   WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:
export LANG=en_US.UTF-8
```
pod install --verbose

```
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:

export LANG=en_US.UTF-8

[!] No `Podfile' found in the project directory.


/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:151:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:46:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```
locale

```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
thanks in advance

**Comment by bitce** [comment]
Hi @ShrutiThakur01!

Sorry to hear about the issue! Can you please include an URL here for a build where you experience this?

**Comment by ShrutiThakur01** [comment]
Hi @bitce 

finally i solved this issue with below steps

1. export LANG=en_US.UTF-8
2. opened project in Xcode and cleaned it.
3. opened iOS folder in mac terminal and ran pod install
4. it gave me warming of using ios 9.0 so i updated it to 10.0
5. ran flutter build iOS
6. project build successfully
7. opened Runner.xcworkspace in xode
8. clicked on run - this time Xcode again installed pod automatically

and Solved.
Thanks :)

**Comment by leventkantaroglu** [comment]
> Hi @bitce
> 
> finally i solved this issue with below steps
> 
> 1. export LANG=en_US.UTF-8
> 2. opened project in Xcode and cleaned it.
> 3. opened iOS folder in mac terminal and ran pod install
> 4. it gave me warming of using ios 9.0 so i updated it to 10.0
> 5. ran flutter build iOS
> 6. project build successfully
> 7. opened Runner.xcworkspace in xode
> 8. clicked on run - this time Xcode again installed pod automatically
> 
> and Solved.
> Thanks :)

I applied same steps, and I am **able to run and build**, thanks. 
But when debuging, I get same errors:

```
CocoaPods' output:
↳
    [!] No `Podfile' found in the project directory.
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:151:in `verify_podfile_exists!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:46:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
        export LANG=en_US.UTF-8
```

**Comment by deliciafernandes** [comment]
Update my zsh shell with UTF-8, still encountering CocoaPods issue

**Comment by Yoni-Reiss** [comment]
Did anyone find any solution?

**Comment by missiorex** [comment]
flutter clean
Delete ios/Flutter/Flutter.framework
pod install

This should work

**Comment by subhangpati** [comment]
Today I encountered the same issue, followed the exact same process. 
only with the addition, after that, I had to change the min ios support from 9.0 to higher. 
@jijuthomas98

**Comment by DurandSacha** [comment]
I used this in terminal
`chcp 65001`

but it's a temporary solution
