### ISSUE TITLE
Support `--deployment` option

### ISSUE THREAD

**Issue by nikolaykasyanov** [bitrise-steplib/steps-cocoapods-install#54]
According to the docs (`pod install --help`):
>Disallow any changes to the Podfile or the Podfile.lock during installation

This might be handy on CI to ensure all changes to `Podfile.lock` are committed. Currently, one has to use a separate script step to perform this check manually.

**Comment by goetzc** [comment]
That's right, this option is very useful, without it, the code on the repository vs the build app can be different. This option ensures consistency halting the build if the file is out-of-sync.

**Comment by non-binary** [comment]
Hi @nikolaykasyanov @goetzc,

Thank you for reaching out.

I have escalated this to the next level of support for consideration.

**Comment by goetzc** [comment]
Still relevant.

**Comment by mefiblogger** [comment]
Hello,

It's Mefi here from the Bitrise CoreSteps Team. Thanks for reaching out helping us and the mobile community to have a better experience with Bitrise steps. 💜

We started to have a broader review of all the open issues and PRs and we are continuously prioritizing these in our sprints.

We reviewed this issue and we found it to be a valid feature request. We are collecting new feature requests on our [Discuss forum](https://discuss.bitrise.io/c/feature-request/) where you can upvote and discuss further details. As this one is on our current roadmap, I close the issue and we'll share an update once we released the new version of the step. Until then, feel free to create a feature request and share your thoughts on Discuss.

Happy building! 🚀
