### ISSUE TITLE
Issue on cocoapods step

### ISSUE THREAD

**Issue by AntonioFerreira94** [bitrise-steplib/steps-cocoapods-install#56]
Hello,

I'm getting an error when cocoapods builds the framework 'WhirlyGlobe', this didn't happen before.
[!] 'libjson' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.
Command failed, error: exit status 1

libjson is a submodule of the WhirlyGlobe.

But then I went to the Logs, and the following was printed:
-> Installing proj4 (4.8.0)
 > Subversion download
   $ /usr/bin/svn export --non-interactive --trust-server-cert --force https://svn.osgeo.org/metacrs/proj/tags/4.8.0 /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20200330-2137-u0lyqk
   svn: error: Failed to locate 'svn'.
   svn: error: The subversion command line tools are no longer provided by Xcode.

[!] Error installing proj4
[!] /usr/bin/svn export --non-interactive --trust-server-cert --force https://svn.osgeo.org/metacrs/proj/tags/4.8.0 /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20200330-2137-u0lyqk

svn: error: Failed to locate 'svn'.
svn: error: The subversion command line tools are no longer provided by Xcode.

Can anyone help me with this?

**Comment by ahvth-bitrise** [comment]
Hi @AntonioFerreira94 

It looks like this install script requires subversion, which you can obtain by running `brew install subversion` in a script stepbefore pod install attempts to reference it.

**Comment by AntonioFerreira94** [comment]
> brew install subversion

Thank you, it fixed the problem! :)
