### ISSUE TITLE
Error from out of date pod repo

### ISSUE THREAD

**Issue by michaelrccurtis** [bitrise-steplib/steps-cocoapods-install#59]
We're getting an error due to the pods repo being outdated:

```[!] CocoaPods could not find compatible versions for pod "Analytics":
  In snapshot (Podfile.lock):
    Analytics (= 4.0.1)
  In Podfile:
    RNAnalytics (from `../node_modules/@segment/analytics-react-native`) was resolved to 1.2.1, which depends on
      Analytics (= 3.9.0)
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Analytics` inside your development pod `RNAnalytics`.
   You should run `pod update Analytics` to apply changes you've made.
```

It looks like the relevant [pod](https://cocoapods.org/pods/Analytics#changelog) was updated on 18/06/2020. My understanding from an old ticket on this repo is that the pods repo gets automatically updated each weekend on the build machines. If so, I'm not sure why this is happening - is this a bug?

Either way, is there a way to force this step to update to run `pod repo update` as part of the build?

**Comment by non-binary** [comment]
Hi @michaelrccurtis,

You can add a Script step right before the CocoaPods step and add pod repo update and it will run it before the CocoaPods step starts.

**Comment by michaelrccurtis** [comment]
Thanks @non-binary! Just to check - is the repo updated automatically still on build devices regularly?

**Comment by non-binary** [comment]
@michaelrccurtis I believe it is updated when we do deployments to the VM infrastructure.
