### ISSUE TITLE
Problem running the step with a Gemfile with cocoapods

### ISSUE THREAD

**Issue by amorino** [bitrise-steplib/steps-cocoapods-install#60]
I have this problem running this step.

```
Determining required cocoapods version
Searching for Podfile.lock
Found Podfile.lock: /Users/vagrant/git/ios/Podfile.lock
Required CocoaPods version (from Podfile.lock): 1.9.1
Searching for gem lockfile with cocoapods gem
No gem lockfile with cocoapods gem found at: 
Using system installed CocoaPods version
Check selected Ruby is installed
Ruby 2.6.5 is installed
Installing cocoapods
Checking cocoapods 1.9.1 gem
Installing
$ gem "install" "cocoapods" "--no-document" "-v" "1.9.1"
Command failed, error: exit status 1
```

I have no verbose log from `gem "install" "cocoapods" "--no-document" "-v" "1.9.1"` so that's all I have.

The build is https://app.bitrise.io/build/e01351f600a0a84d if someone can check it.

I ran the command `gem "install" "cocoapods" "--no-document" "-v" "1.9.1"` from Remote Access successfully.

Some things to have in mind is that I have a Gemfile in the root of the project with cocoapods as dependency and the Podfile is on the folder /ios/, the step doesn't seem to find that Gemfile.

**Comment by non-binary** [comment]
Hi @amorino,

Can you try doing the same command as a Script step to see if it fails or succeeds? If fails, this could be a bug in the step.

**Comment by amorino** [comment]
I think resolve the error.

I have a file .ruby-version on `ios` folder, it always fails because of that, the Bitrise machine doesn't find the correct version. If I run the command from outside of that folder, the command always runs fine. The thing is that the command is running from inside the `ios` folder because there's the place where the Podfile exists.

It is not a big deal at the end because I found the issue, but is it possible to verbose also what is happening with the `gem install` command?

**Comment by non-binary** [comment]
I will create a ticket for the engineering team to look at this at some point in the future.

**Comment by SaezChristopher** [comment]
same problem here

**Comment by non-binary** [comment]
This has not been worked on yet.
