### ISSUE TITLE
build fails with podfile related to react native

### ISSUE THREAD

**Issue by sk92129** [bitrise-steplib/steps-cocoapods-install#62]
I am new to bitrise and this is my first project to build on bitrise.

I took care of the code signing portion and got past that. 
Now this podfile failure is happening.  I am not sure what is causing this because the react-native app build works locally on my macbook.

[32;1m$ pod "_1.9.1_" "install" "--verbose"[0m

[!] Invalid `Podfile` file: cannot load such file -- /Users/vagrant/git/node_modules/react-native/scripts/react_native_pods.

 #  from /Users/vagrant/git/ios/Podfile:1
 #  -------------------------------------------
 >  require_relative '../node_modules/react-native/scripts/react_native_pods'
 #  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  -------------------------------------------

/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/podfile.rb:301:in `rescue in block in from_ruby'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/podfile.rb:295:in `block in from_ruby'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/podfile.rb:50:in `initialize'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/podfile.rb:293:in `new'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/podfile.rb:293:in `from_ruby'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/podfile.rb:259:in `from_file'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/config.rb:200:in `podfile'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:46:in `run'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/vagrant/.rbenv/versions/2.6.5/bin/pod:23:in `load'
/Users/vagrant/.rbenv/versions/2.6.5/bin/pod:23:in `<main>'
[31;1mCommand failed, error: exit status 1[0m
|                                                                              |
+---+---------------------------------------------------------------+----------+
| [31;1mx[0m | [31;1mcocoapods-install@1 (exit code: 1)[0m                            | 1.7 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-cocoapods-install/issues  |
| Source: https://github.com/bitrise-io/steps-cocoapods-install                |
+---+---------------------------------------------------------------+----------+

This is a sample react-native project but I was kicking the tires on bitrise to get a RN app fully configured on bitrise.

[a0dae8386cd3f5f5.log](https://github.com/bitrise-steplib/steps-cocoapods-install/files/5611193/a0dae8386cd3f5f5.log)

**Comment by non-binary** [comment]
Hi @sk92129,

Can you please provide a link to a build and enable support access?

Additionally, can you provide your Podfile in a gist.github.com?

**Comment by sk92129** [comment]
This is the link to the app on my “org” dashboard.

https://app.bitrise.io/app/d786536fcc79416a#/builds


this is the podfile:

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'eddie2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'eddie2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'eddie2-tvOS' do
  # Pods for eddie2-tvOS

  target 'eddie2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

**Comment by non-binary** [comment]
Can you please enable support access?

**Comment by trisapeace** [comment]
@non-binary , I am having the same issue as @sk92129 

I have enabled the Support user on my app: https://app.bitrise.io/app/c31c3ce97661f8d7#/builds

The podfile is https://gist.github.com/trisapeace/704ddf37266d445886734a8e0d5fe715

Thank you!

**Comment by trisapeace** [comment]
@sk92129 , I got around this issue by adding a script to my workflow before the "Run Cocoapods install" that simply calls `npm install`. This created the `/Users/vagrant/git/node_modules/react-native/scripts/react_native_pods.rb` file that it appears to be looking for.
