### ISSUE TITLE
Error fetching https://github.com/jcouball/ruby-git.git

### ISSUE THREAD

**Issue by microeditionbiz** [bitrise-steplib/steps-cocoapods-install#74]
### Troubleshooting

- [✔️] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.2.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Every time I try to execute "Run CocoaPods install" I get this error:

```
Installing cocoapods with bundler
$ bundle "_2.0.2_" "install" "--jobs" "20" "--retry" "5"

Fetching gem metadata from https://rubygems.org/........
Fetching https://github.com/jcouball/ruby-git.git
fatal: Could not parse object '65a2853ae7cc89b7006ed05d00982f36163845fa'.
Revision 65a2853ae7cc89b7006ed05d00982f36163845fa does not exist in the
repository https://github.com/jcouball/ruby-git.git. Maybe you misspelled it?
Command failed, error: exit status 11
```

I don't have a Podfile.lock or Gemfile.lock on my repository. It seem that is using the ones stored in `/Users/vagrant/git/Example/Podfile.lock` and `/Users/vagrant/git/Example/Gemfile.lock`

### Bitrise info

- Build URL: https://app.bitrise.io/build/ddf872bdc11e7e77
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>

+------------------------------------------------------------------------------+

| (4) cocoapods-install                                                        |
+------------------------------------------------------------------------------+
| id: cocoapods-install                                                        |
| version: 2.2.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-06-22T09:26:00Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
ConfigsModel:
- Command: install
- SourceRootPath: /Users/vagrant/git
- PodfilePath: 
- Verbose: true
- IsCacheDisabled: false
Searching for Podfile
Found Podfile: /Users/vagrant/git/Example/Podfile
Determining required cocoapods version
Searching for Podfile.lock
Found Podfile.lock: /Users/vagrant/git/Example/Podfile.lock
Required CocoaPods version (from Podfile.lock): 1.9.3
Searching for gem lockfile with cocoapods gem
Found gem lockfile: /Users/vagrant/git/Example/Gemfile.lock
Required CocoaPods version (from gem lockfile): 1.9.3
Check selected Ruby is installed
Ruby 2.5.1 is not installed
$ rbenv "install" "2.5.1"
Downloading openssl-1.1.1k.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/892a0875b9872acd04a9fde79b1f943075d5ea162415de3047c327df33fbaee5
Installing openssl-1.1.1k...
Installed openssl-1.1.1k to /Users/vagrant/.rbenv/versions/2.5.1
Downloading ruby-2.5.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.bz2
Installing ruby-2.5.1...
WARNING: ruby-2.5.1 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.
ruby-build: using readline from homebrew
Installed ruby-2.5.1 to /Users/vagrant/.rbenv/versions/2.5.1
Installing cocoapods
Installing bundler
$ gem "install" "bundler" "--force" "--no-document" "--version" "2.0.2"
Successfully installed bundler-2.0.2
1 gem installed
Installing cocoapods with bundler
$ bundle "_2.0.2_" "install" "--jobs" "20" "--retry" "5"
Fetching gem metadata from https://rubygems.org/........
Fetching https://github.com/jcouball/ruby-git.git
fatal: Could not parse object '65a2853ae7cc89b7006ed05d00982f36163845fa'.
Revision 65a2853ae7cc89b7006ed05d00982f36163845fa does not exist in the
repository https://github.com/jcouball/ruby-git.git. Maybe you misspelled it?
Command failed, error: exit status 11
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | cocoapods-install (exit code: 1)                              | 4.6 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-cocoapods-install/issues  |
| Source: https://github.com/bitrise-io/steps-cocoapods-install                |
+---+---------------------------------------------------------------+----------+

  </pre>
</details>

### Steps to reproduce

Just try to execute current workflow.

**Comment by Roland-Bak** [comment]
Hello there @microeditionbiz 👋

It seems that the source of the issue is trying to download a certain commit from https://github.com/jcouball/ruby-git, but it is not defined properly in your Gemfile.lock, which is located in /Users/vagrant/git/Example/Gemfile.lock. Could you double check this, and perhaps try to define a different commmit, to see if it works? 🙂

**Comment by microeditionbiz** [comment]
Hi @Roland-Bak, thanks for your answer.

I was having similar thoughts. The thing is that Gemfile.lock is located inside the build machine right? Do I have a way to modify that one?
