### ISSUE TITLE
Cocoa pods install different libraries versions than it is stated in podfile

### ISSUE THREAD

**Issue by davidcz95** [bitrise-steplib/steps-cocoapods-install#76]
### Troubleshooting

- I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.

- Which version of the step is effected? 2.2.0
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Issue description

Hello,
The issue is that when running cocoa pods with pod install on bitrise i gives an error:
<details>
  <pre>
Analyzing dependencies
firebase_analytics: Using Firebase SDK version '8.3.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.3.0' defined in 'firebase_core'
firebase_crashlytics: Using Firebase SDK version '8.3.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In snapshot (Podfile.lock):
    Firebase/Analytics (= 8.0.0)
  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 8.2.0, which depends on
      Firebase/Analytics (= 8.3.0)
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Firebase/Analytics` inside your development pod `firebase_analytics`.
   You should run `pod update Firebase/Analytics` to apply changes you've made.
command failed, error: pod install failed: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | cocoapods-install@2 (exit code: 1)                            | 2.7 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-cocoapods-install/issues  |
| Source: https://github.com/bitrise-io/steps-cocoapods-install                |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

When running cocoa pods with pod update it goes through but somehow installing different libs versions that stated in podfile.lock

This is the output when I run pod install locally:
 <details>
  <pre>
firebase_analytics: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
firebase_crashlytics: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
Downloading dependencies
Installing CocoaLumberjack (3.7.2)
Installing FBSDKCoreKit (9.1.0)
Installing FMDB (2.7.5)
Installing Firebase (8.0.0)
Installing FirebaseAnalytics (8.0.0)
Installing FirebaseCore (8.0.0)
Installing FirebaseCoreDiagnostics (8.4.0)
Installing FirebaseCrashlytics (8.0.0)
Installing FirebaseInstallations (8.4.0)
Installing Flutter (1.0.0)
Installing GoogleAppMeasurement (8.0.0)
Installing GoogleDataTransport (9.1.0)
Installing GoogleMaps (4.2.0)
Installing GoogleUtilities (7.5.0)
Installing PromisesObjC (1.2.12)
Installing TOCropViewController (2.6.0)
Installing app_tracking_transparency (0.0.1)
Installing audio_service (0.0.1)
Installing audio_session (0.0.1)
Installing background_fetch (1.0.1)
Installing background_locator (0.0.1)
Installing facebook_app_events (0.0.1)
Installing firebase_analytics (8.1.0)
Installing firebase_core (1.2.0)
Installing firebase_crashlytics (2.0.4)
Installing flutter_background_geolocation (4.0.2)
Installing flutter_inapp_purchase (0.0.1)
Installing flutter_isolate (0.0.1)
Installing flutter_secure_storage (3.3.1)
Installing geolocator (6.2.0)
Installing google_maps_flutter (0.0.1)
Installing image_cropper (0.0.4)
Installing image_picker (0.0.1)
Installing just_audio (0.0.1)
Installing location (0.0.1)
Installing location_permissions (3.0.0+1)
Installing nanopb (2.30908.0)
Installing package_info (0.0.1)
Installing path_provider (0.0.1)
Installing permission_handler (5.1.0+2)
Installing rate_my_app (1.1.0)
Installing share_plus (0.0.1)
Installing shared_preferences (0.0.1)
Installing sqflite (0.0.2)
Installing url_launcher (0.0.1)
Installing video_player (0.0.1)
Installing wakelock (0.0.1)
Installing webview_flutter (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 32 dependencies from the Podfile and 48 total pods installed.
  </pre>
</details>

And this is the output when run in bitrise pod update:
<details>
  <pre>
Installing Pods
$ pod "_1.10.1_" "update" "--no-repo-update"
Update all pods
Analyzing dependencies
firebase_analytics: Using Firebase SDK version '8.3.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.3.0' defined in 'firebase_core'
firebase_crashlytics: Using Firebase SDK version '8.3.0' defined in 'firebase_core'
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
Downloading dependencies
Installing CocoaLumberjack (3.7.2)
Installing FBSDKCoreKit (9.1.0)
Installing FMDB (2.7.5)
Installing Firebase (8.3.0)
Installing FirebaseAnalytics (8.3.0)
Installing FirebaseCore (8.3.0)
Installing FirebaseCoreDiagnostics (8.4.0)
Installing FirebaseCrashlytics (8.3.0)
Installing FirebaseInstallations (8.4.0)
Installing Flutter (1.0.0)
Installing GoogleAppMeasurement (8.3.0)
Installing GoogleDataTransport (9.1.0)
Installing GoogleMaps (4.2.0)
Installing GoogleUtilities (7.5.0)
Installing PromisesObjC (1.2.12)
Installing TOCropViewController (2.6.0)
Installing app_tracking_transparency (0.0.1)
Installing audio_service (0.0.1)
Installing audio_session (0.0.1)
Installing background_fetch (1.0.1)
Installing background_locator (0.0.1)
Installing facebook_app_events (0.0.1)
Installing firebase_analytics (8.2.0)
Installing firebase_core (1.4.0)
Installing firebase_crashlytics (2.1.1)
Installing flutter_background_geolocation (4.0.2)
Installing flutter_inapp_purchase (0.0.1)
Installing flutter_isolate (0.0.1)
Installing flutter_secure_storage (3.3.1)
Installing geolocator (6.2.0)
Installing google_maps_flutter (0.0.1)
Installing image_cropper (0.0.4)
Installing image_picker (0.0.1)
Installing just_audio (0.0.1)
Installing location (0.0.1)
Installing location_permissions (3.0.0+1)
Installing nanopb (2.30908.0)
Installing package_info (0.0.1)
Installing path_provider (0.0.1)
Installing permission_handler (5.1.0+2)
Installing rate_my_app (1.1.1)
Installing share_plus (0.0.1)
Installing shared_preferences (0.0.1)
Installing sqflite (0.0.2)
Installing url_launcher (0.0.1)
Installing video_player (0.0.1)
Installing wakelock (0.0.1)
Installing webview_flutter (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 32 dependencies from the Podfile and 48 total pods installed.
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
Collecting Pod cache paths...
Success!
  </pre>
</details>

As you can see library version number are higher in bitrise and I don't want that as it breaks some of my app features.
Any advice/tips/feedback will be much appreciated.

### Bitrise info
- [Bitrise Support] enabled: YES

**Comment by FilipTrzaska** [comment]
We have the same problem.

**Comment by Roland-Bak** [comment]
Hello there 👋


Can you please send us the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/en/apps/enabling-the-bitrise-support-user-for-your-app.html ) so that we can take a more in-depth look? 🙂
