### ISSUE TITLE
CocoaPods-Install tries to install ruby via rbenv even if using suggested asdf

### ISSUE THREAD

**Issue by broksonic21** [bitrise-steplib/steps-cocoapods-install#98]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time?  EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Issue description

See https://github.com/bitrise-io/go-steputils/blob/v1.0.5/command/rubycommand/rubycommand.go#L69-L77

which prefers rbenv over asdf

However, https://discuss.bitrise.io/t/xcode-14-3-x-edge-stack-update-2023-06/22945 suggests using asdf over Rbenv

but if you do, the RubyCommand still finds rbenv and thinks it needs to use it. This causes steps, like cocoa pods-install (see [https://github.com/bitrise-steplib/steps-cocoapods-install/blob/75dd45d47a09aecdec2f90738ebb78afc677a8dd/main.go#L368 ](https://github.com/bitrise-steplib/steps-cocoapods-install/blob/75dd45d47a09aecdec2f90738ebb78afc677a8dd/main.go#L368)) to try and install Ruby again even if it's there from asdf

Also filed vs RubyCommand here: [https://github.com/bitrise-io/go-steputils/issues/83]( https://github.com/bitrise-io/go-steputils/issues/83)

**Comment by lpusok** [comment]
Released https://github.com/bitrise-steplib/steps-cocoapods-install/releases/tag/2.4.0 with a fix.
