### ISSUE TITLE
Error with Xcode 15 and cocoapods 1.12.1

### ISSUE THREAD

**Issue by fcazorlameca** [bitrise-steplib/steps-cocoapods-install#99]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.4.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO

### Useful information

- [FAQ](https://github.com/CocoaPods/CocoaPods/releases/tag/1.13.0)

### Issue description

The cocoapods install step completes correctly but when using cocoapods version 1.12.1 and the new Xcode 15 an error occurs when trying to archive the ipa. This error is fixed in the latest version of cocoapods 1.13 as indicated in its new release, and I have checked it by performing the archive locally with the new version of cocoapods.

### Bitrise info

- Log: 
<details>
  <pre>
 ❌  error: DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'FirebaseAnalytics' from project 'Pods')

  </pre>
</details>

Thanks you

**Comment by EBaglieriSkylabs** [comment]
Same issue.

**Comment by denysgalante** [comment]
I also have the same problem, please Bitrise team update virtual machines with new version of cocoapods 1.13.0

**Comment by fcazorlameca** [comment]
I have fixed this by adding a specific version of cocoapods to the Gemfile to force it to use this version.

Add this in code Gemfile

`gem 'cocoapods', '~> 1.13'`

and run bundle install to generate Gemfile.lock
